#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int sum_fib_sequence(int limit);
int digit_product(int num);
int get_number(int max, int min);
int roll_one_die();
void roll_dice_pair(int *die1, int *die2);
int play_one_round(int numb);

int main() {
    printf("%d\n",sum_fib_sequence(20));
    printf("%d\n",digit_product(20));
    printf("%d\n", get_number(100, 0));
    srand(time(0));
    printf("%d\n", play_one_round(5));

    return 0;
}

/* Purpose: Create a fib siquence until a certain limit
 *
 * Parameters: Three integer values which are nex (next number to the current counter), prev (previous number), num (current counter), sum (sum of previous and current counters
 *
 * Returns: An integer value which is the summ of the fibonacci numbers until the limit.
 * 
 */

int sum_fib_sequence(int limit) {
    int nex = 1;
    int prev;
    int sum = 0;
    for(int num=0; num<=limit; nex=num+prev) {
        sum += num;
        prev=num;
        num=nex;
    }
    
    return sum;
}

/* Purpose: Take products of digits inside a number
 *
 * Parameters: absnum (absolute value of the number), number (the value given in the argument), rem (remainder of the counter), n (remaining digits with number after each counter), prod (products of the digits after each counter)
 *
 * Returns: Returns the integer final product of the number.
 * 
 */

int digit_product(int num) {
    int absnum;
    if (num<0) {
        absnum = -num;
    } else {
        absnum = num;
    }

    int rem=0; 
    int prod = 1;
    for (int n = absnum; n!=0; prod*=rem) {
        rem=n%10;
        n-=rem;
        n=n/10;
    }
    return prod;
}

/* Purpose: Returns a value if it's smaller than a maximum argument integer value and bigger than a minimum value.
 *
 * Parameters: scanned1 (returns 1 if scanned any integer number, otherwise 0), scanned2 (returns 1 if typed any character number, otherwise 0), c (characters), n (numbers), min (minimum integer value input in the argument) max (maximum integer value input in the argument).
 *
 * Returns: An integer value that's smaller than max and greater than min.
 * 
 */

int get_number(int max, int min) {
    int n = 0;
    int c;
    int scanned1, scanned2;
    printf("Enter a number smaller than %d and greater than %d\n", max, min);
    scanned1 = scanf("%d", &n);
    scanned2 = scanf("%lc", &c);

    if (scanned1==1) {
        while (((n>max)||(n<min))&&(scanned1==1)) {
            printf("Err: Enter a number smaller than %d and greater than %d\n", max, min);
            scanned1 = scanf("%d", &n);
                while (scanned1!=1) {
                scanned2 = scanf("%lc", &c);
                scanned1 = scanf("%d", &n);    
            }
    }
    } else if (scanned2==1) {
        while (scanned1!=1) {
            scanned2 = scanf("%lc", &c);
            scanned1 = scanf("%d", &n);    
        }
        while (((n>max)||(n<min))&&(scanned1==1)) {
            printf("Err: Enter a number smaller than %d and greater than %d\n", max, min);
            scanned1 = scanf("%d", &n);
                while (scanned1!=1) {
                scanned2 = scanf("%lc", &c);
                scanned1 = scanf("%d", &n);    
            }
        }
    }

    return n;
}

/* Purpose: Makes a random number between 1 and 6.
 *
 * Parameters: random_number (A number that's randomly generated by strand()), die (A number that takes into account the real values in the rolling dice, in our case, 1-6)
 *
 * Returns: The integer value of the variable die
 * 
 */

int roll_one_die()  {
    int random_number = rand() % 6;
    int die = random_number + 1;
    return die;
}

/* Purpose: Creates two pointer values, stores the pointers as integer addresses to be two random numbers between 1 and 6.
 *
 * Parameters: Two Pointers *die1 and *die2, which are two dice values randomly generated.
 *
 * Returns: Doesn't return a value.
 */

void roll_dice_pair(int *die1, int *die2)   {
    *die1 = roll_one_die();
    *die2 = roll_one_die();
}

/* Purpose: Creates two values for dices and asks the user to guess the number (argument integer value), and tells if they wins or losses.
 *
 * Parameters: a (Random number generated by first roll dice), b (Random number generated by second roll dice), val (The return binary value of whether the player loses or wins), *die1 (Address of the integer value of a), *die2 (Address of the integer value of b), numb (Value guessed by the user), targ(sum of the newly generated random roll dices, generated for the second chance in the game).
 *
 * Returns:
 * 
 */

int play_one_round(int numb) {
    int a, b, val;
    roll_dice_pair(&a, &b);
    int* die1 = &a;
    int* die2 = &b;

    printf("You guessed %d. Rolling!\n\nRolled %d and %d\n\n", numb, *die1, *die2);

    if (a==b) {
        int targ = a + b;
        printf("You are getting a second chance!\n\nYou want one of your dice to be %d. You don't want the total to equal %d or your second chance is over.\n\n", numb, targ);
        roll_dice_pair(&a, &b);
        printf("Rolled %d and %d.\n\n", *die1, *die2); 

        while ((numb!=a)&&(numb!=b)&&(targ!=a+b)) {
            roll_dice_pair(&a, &b); 
            printf("Rolled %d and %d.\n\n", *die1, *die2);  
        }
        if ((numb==a)||(numb==b)) {
            printf("You won!\n");
            val = 1;
        } else if (targ==a+b) {
            printf("You lost!\n");
            val = 0;
        }

    } else if (a!=b) {
        if ((numb==a)||(numb==b)) {
            printf("You won!\n");
            val = 1;
        } else {
            printf("You lost!\n");
            val = 0;
        }
    }
    
    return val;
}